let cards = [
    {
        popular: true, 
        id: 1,
        image: 'image/Rectangle 1.png',
        header: 'Париж',
        text: '9 дней | 12 дней поездка в Нормандию и Париж',
        actualPrice: 138000,
        notActualPrice: '150 000 руб',
        button: 'Выбрать',
    },
    {
        popular: true, 
        id: 2,
        image: 'image/Rectangle 22.png',
        header: 'Италия, Манарола',
        text: '12 дней | 14 дней с поездкой в Рим',
        actualPrice: 175000,
        notActualPrice: '190 000 руб',
        button: 'Выбрать',
    },
    {
        popular: true, 
        id: 3,
        image: 'image/Rectangle 23.png',
        header: 'Италия, Рим',
        text: '11 дней | 14 дней с поездкой в Мадрид',
        actualPrice: 200000,
        notActualPrice: '230 000 руб',
        button: 'Выбрать',
    },
    {
        popular: false, 
        id: 4,
        image: 'image/Rectangle 24.png',
        header: 'Италия, Венеция',
        text: '9 дней | 11 дней с поездкой на полуостров Сорренто',
        actualPrice: 155000,
        notActualPrice: '177 000 руб',
        button: 'Выбрать',
    },
    {
        popular: false, 
        id: 5,
        image: 'image/Rectangle 25.png',
        header: 'Тур по Испании',
        text: '14 дней | 16 дней с поездкой в Барселону',
        actualPrice: 200000,
        notActualPrice: '210 000 руб',
        button: 'Выбрать',
    },
    {
        popular: false, 
        id: 6,
        image: 'image/Rectangle 26.png',
        header: 'Бразилия, Рио',
        text: 'Рио, водопады Игуасу и Буэнос-Айрес',
        actualPrice: 225000,
        notActualPrice: '240 000 руб',
        button: 'Выбрать',
    },
    {
        popular: false, 
        id: 7,
        image: 'image/Rectangle 27.png',
        header: 'Хельсинки',
        text: 'Скандинавия: столицы и фьорды',
        actualPrice: 215000,
        notActualPrice: '230 000 руб',
        button: 'Выбрать',
    },
    {
        popular: false, 
        id: 8,
        image: 'image/Rectangle 28.png',
        header: 'Лондон',
        text: '9 дней | 11 дней с поездкой в Париж',
        actualPrice: 285000,
        notActualPrice: '295 000 руб',
        button: 'Выбрать',
    },
    {
        popular: false, 
        id: 9,
        image: 'image/Rectangle 29.png',
        header: 'Аляска',
        text: 'Национальный парк Денали и круиз по дикой Аляске',
        actualPrice: 300000,
        notActualPrice: '310 000 руб',
        button: 'Выбрать',
    }
];