let cards = [
    {
        id: 1,
        image: 'image/Rectangle 22 (1).png',
        header: 'Италия, Венеция',
        text: '9 дней | 11 дней с поездкой на полуостров Сорренто',
        actualPrice: 155000,
        notActualPrice: '177 000 руб',
        button: 'Выбрать',
    },
    {
        id: 2,
        image: 'image/Rectangle 22 (2).png',
        header: 'Тур по Испании',
        text: '14 дней | 16 дней с поездкой в Барселону',
        actualPrice: 200000,
        notActualPrice: '210 000 руб',
        button: 'Выбрать',
    },
    {
        id: 3,
        image: 'image/Rectangle 22 (3).png',
        header: 'Бразилия, Рио',
        text: 'Рио, водопады Игуасу и Буэнос-Айрес',
        actualPrice: 225000,
        notActualPrice: '240 000 руб',
        button: 'Выбрать',
    },
    {
        id: 4,
        image: 'image/Rectangle 22 (4).png',
        header: 'Хельсинки',
        text: 'Скандинавия: столицы и фьорды',
        actualPrice: 215000,
        notActualPrice: '230 000 руб',
        button: 'Выбрать',
    },
    {
        id: 5,
        image: 'image/Rectangle 22 (5).png',
        header: 'Лондон',
        text: '9 дней | 11 дней с поездкой в Париж',
        actualPrice: 285000,
        notActualPrice: '295 000 руб',
        button: 'Выбрать',
    },
    {
        id: 6,
        image: 'image/Rectangle 22 (6).png',
        header: 'Аляска',
        text: 'Национальный парк Денали и круиз по дикой Аляске',
        actualPrice: 300000,
        notActualPrice: '310 000 руб',
        button: 'Выбрать',
    },
    {
        id: 7,
        image: 'image/Rectangle 22 (7).png',
        header: 'Париж',
        text: '9 дней | 12 дней с поездкой в Нормандию и Париж',
        actualPrice: 138000,
        notActualPrice: '150 000 руб',
        button: 'Выбрать',
    },
    {
        id: 8,
        image: 'image/Rectangle 22 (8).png',
        header: 'Италия, Манарола',
        text: '12 дней | 14 дней с поездкой в Рим',
        actualPrice: 175000,
        notActualPrice: '190 000 руб',
        button: 'Выбрать',
    },
    {
        id: 9,
        image: 'image/Rectangle 22 (9).png',
        header: 'Италия, Рим',
        text: '11 дней | 14 дней с поездкой в Мадрид',
        actualPrice: 200000,
        notActualPrice: '230 000 руб',
        button: 'Выбрать',
    },
    {
        id: 10,
        image: 'image/Rectangle 22 (10).png',
        header: 'Парки США, Гранд-Каньон',
        text: '12 дней | 15 дней с Национальным парком Миссула и Глейшер',
        actualPrice: 185000,
        notActualPrice: '197 000 руб',
        button: 'Выбрать',
    },
    {
        id: 11,
        image: 'image/Rectangle 22 (11).png',
        header: 'Польша, Прага',
        text: '9 дней | 11 дней с поездкой в Будапешт',
        actualPrice: 285000,
        notActualPrice: '305 000 руб',
        button: 'Выбрать',
    },
    {
        id: 12,
        image: 'image/Rectangle 22 (12).png',
        header: 'Греция, Крит',
        text: '14 дней | 16 дней с поездкой в Афины, Миконос, Санторини и Крит',
        actualPrice: 320000,
        notActualPrice: '340 000 руб',
        button: 'Выбрать',
    }
];